// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies which role registry supplied a spawned agent's persisted role definition.
 *
 * Consumers must use this value when reloading a spawned thread instead of inferring provenance
 * from the current configuration, because user-defined roles can shadow built-in role names.
 */
export type AgentRoleProvenance = "built_in" | "user_defined";
