// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationSubAgentSource } from "./ConversationSubAgentSource";
import type { InternalSessionSource } from "./InternalSessionSource";

export type SessionSource = "cli" | "vscode" | "exec" | "mcp" | { "custom": string } | { "internal": InternalSessionSource } | { "subagent": ConversationSubAgentSource } | "unknown";
